version: '3.1'
services:
    node:
        build: dockerfiles
        container_name: node-api
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        ports:
            - '4001:4001'

    postgres:
        image: postgres
        container_name: postgres
        environment:
            POSTGRES_PASSWORD: 'pg@tiger!1234'
        ports:
            - '5432:5432'

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'
