services:
    node:
        build: dockerfiles
        container_name: bts-node
        working_dir: /usr/src/app
        restart: always
        volumes:
            - .:/usr/src/app
        ports:
            - '4001:4001'

    postgres:
        image: postgres
        container_name: bts-pgsl
        environment:
            POSTGRES_PASSWORD: 'pg@tiger!1234'
        ports:
            - '5432:5432'

    redis:
        image: redis:latest
        container_name: bts-redis
        ports:
            - '6379:6379'
